apiVersion: v1
kind: Secret
metadata:
  name: iotconsumer-sc
type: Opaque
data:
  dbpwd: <your encoded value>                 
  iotauthkey: <your encoded value> 
  iotauthtoken: <your encoded value>
  database: <your encoded value>
  dbtable: <your encoded value>
  dbport: <your encoded value>
  dbuid: <your encoded value>
  dbhostname: <your encoded value>
  iotorg: <your encoded value>
